services:
  devices-api-dev.seq:
    image: datalust/seq:2024.3
    container_name: devices-api-dev-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
  
  sensor-fushion-hub-jaeger:
    image: jaegertracing/all-in-one:1.60
    container_name: sensor-fushion-hub-jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686